"""API tests for the async plan-generation behaviour of the onboarding endpoint.

The Phase-2.7 Batch 3 plan (closing G-03) decouples plan generation
from the onboarding transaction. After ``POST /athletes/{id}/onboarding``
returns 201:

* The plan is NOT yet in the database — it is generated by a deferred
  ``generate_plan`` procrastinate task that runs after the onboarding
  commit (and possibly in a separate process).
* ``GET /athletes/{id}/plan`` therefore returns 404 in the window
  between onboarding and the worker task completing.

These tests exercise that contract through the public HTTP surface.

Reference plan: ``docs/implementation/phase-2/phase-2-7/batch-3-event-flow-plan-router-fix.md``
Scenarios 5–6.
"""

from __future__ import annotations

import uuid

from httpx import AsyncClient

from tests.payloads import onboarding_payload
from tests.utils.http_helpers import bearer_header, http_register


class TestOnboardingAsyncPlanGeneration:
    """``POST /onboarding`` returns 201 before the ``generate_plan``
    task runs; ``GET /plan`` returns 404 in the same window."""

    async def test_post_onboarding_returns_201(
        self,
        client: AsyncClient,
    ) -> None:
        aid, tok = await http_register(
            client, f"async-onb-201-{uuid.uuid4()}@example.com"
        )

        response = await client.post(
            f"/api/v1/athletes/{aid}/onboarding",
            json=onboarding_payload(),
            headers=bearer_header(tok),
        )

        assert response.status_code == 201, response.text
        body = response.json()
        assert body["onboarding_complete"] is True
        assert body["twin_state_id"] is not None
        assert body["training_goal_id"] is not None

    async def test_get_plan_returns_404_immediately_after_onboarding(
        self,
        client: AsyncClient,
    ) -> None:
        aid, tok = await http_register(
            client, f"async-onb-404-{uuid.uuid4()}@example.com"
        )
        onboarding_resp = await client.post(
            f"/api/v1/athletes/{aid}/onboarding",
            json=onboarding_payload(),
            headers=bearer_header(tok),
        )
        assert onboarding_resp.status_code == 201

        plan_resp = await client.get(
            f"/api/v1/athletes/{aid}/plan",
            headers=bearer_header(tok),
        )

        assert plan_resp.status_code == 404
        assert "No active training plan" in plan_resp.json()["detail"]

    async def test_response_does_not_include_plan_fields(
        self,
        client: AsyncClient,
    ) -> None:
        """The 201 body must not include plan-related fields — plan
        generation is decoupled from the response."""
        aid, tok = await http_register(
            client, f"async-onb-shape-{uuid.uuid4()}@example.com"
        )

        response = await client.post(
            f"/api/v1/athletes/{aid}/onboarding",
            json=onboarding_payload(),
            headers=bearer_header(tok),
        )

        assert response.status_code == 201
        body = response.json()
        assert "training_plan_id" not in body
        assert "plan" not in body
        assert "plan_pending" not in body
