"""Pydantic schemas for the public API."""

from app.schemas.auth import (
    AthleteResponse,
    AuthResponse,
    LoginRequest,
    RefreshRequest,
    RefreshResponse,
    RegisterProfileIn,
    RegisterRequest,
    TokenPairResponse,
)
from app.schemas.coaching import (
    CoachingMessageResponse,
    FirstMessageConflictResponse,
    MessagesListResponse,
)
from app.schemas.onboarding import (
    AthletePreferencesPatchIn,
    AthletePreferencesResponse,
    AthleteProfilePatchIn,
    AthleteProfileResponse,
    OnboardingPreferencesIn,
    OnboardingProfileIn,
    OnboardingRequest,
    OnboardingResponse,
    OnboardingStatusResponse,
    OnboardingTrainingGoalIn,
    TwinStateHistoryResponse,
    TwinStateResponse,
    WeeklyScheduleDayIn,
    WeeklyScheduleDayOut,
    WeeklyScheduleDayPatchIn,
)
from app.schemas.plan import (
    CheckpointResponse,
    PhaseDescriptorResponse,
    PlannedSessionResponse,
    TrainingPlanResponse,
    UpcomingSessionsResponse,
)

__all__ = [
    "AthletePreferencesPatchIn",
    "AthletePreferencesResponse",
    "AthleteProfilePatchIn",
    "AthleteProfileResponse",
    "AthleteResponse",
    "AuthResponse",
    "CheckpointResponse",
    "CoachingMessageResponse",
    "FirstMessageConflictResponse",
    "LoginRequest",
    "MessagesListResponse",
    "OnboardingPreferencesIn",
    "OnboardingProfileIn",
    "OnboardingRequest",
    "OnboardingResponse",
    "OnboardingStatusResponse",
    "OnboardingTrainingGoalIn",
    "PhaseDescriptorResponse",
    "PlannedSessionResponse",
    "RefreshRequest",
    "RefreshResponse",
    "RegisterProfileIn",
    "RegisterRequest",
    "TokenPairResponse",
    "TrainingPlanResponse",
    "TwinStateHistoryResponse",
    "TwinStateResponse",
    "UpcomingSessionsResponse",
    "WeeklyScheduleDayIn",
    "WeeklyScheduleDayOut",
    "WeeklyScheduleDayPatchIn",
]