"""Pydantic schemas for the public API."""

from app.schemas.auth import (
    AthleteResponse,
    AuthResponse,
    LoginRequest,
    RefreshRequest,
    RefreshResponse,
    RegisterProfileIn,
    RegisterRequest,
    TokenPairResponse,
)
from app.schemas.onboarding import (
    AthletePreferencesPatchIn,
    AthletePreferencesResponse,
    AthleteProfilePatchIn,
    AthleteProfileResponse,
    OnboardingPreferencesIn,
    OnboardingProfileIn,
    OnboardingRequest,
    OnboardingResponse,
    OnboardingStatusResponse,
    OnboardingTrainingGoalIn,
    TwinStateHistoryResponse,
    TwinStateResponse,
    WeeklyScheduleDayIn,
    WeeklyScheduleDayOut,
)

__all__ = [
    "AthletePreferencesPatchIn",
    "AthletePreferencesResponse",
    "AthleteProfilePatchIn",
    "AthleteProfileResponse",
    "AthleteResponse",
    "AuthResponse",
    "LoginRequest",
    "OnboardingPreferencesIn",
    "OnboardingProfileIn",
    "OnboardingRequest",
    "OnboardingResponse",
    "OnboardingStatusResponse",
    "OnboardingTrainingGoalIn",
    "RefreshRequest",
    "RefreshResponse",
    "RegisterProfileIn",
    "RegisterRequest",
    "TokenPairResponse",
    "TwinStateHistoryResponse",
    "TwinStateResponse",
    "WeeklyScheduleDayIn",
    "WeeklyScheduleDayOut",
]
