"""phase_1_2b_plans_sessions_checkpoints

Phase-1.2b schema-only migration: brings up the training plan hierarchy
persistence surface — ``TrainingGoal``, ``SecondaryEvent``,
``RegenerationTask``, ``TrainingPlan``, ``WeeklyPlan``, ``WeeklySession``,
``PlannedSession``, ``Checkpoint`` — and wires the FK from the existing
``activities.planned_session_id`` column to the new ``planned_sessions``
table.

This plan owns schema only. No plan generation, session lifecycle, FIT
ingest, public APIs, services, repositories, tasks, agents, or event
publishers are added here. The plan's exit gate is proven by the
inspection tests in ``tests/integration/test_migration_phase_1_2b.py``
plus the unit-level column-isolation tests in
``tests/unit/test_*_columns.py``.

``training_plans.twin_state_id`` is present as a nullable column but
WITHOUT a foreign key — the FK is added in Phase-1.2c once the
``twin_states`` table exists. Adding the FK now would couple this
plan to a future sub-phase and risk a forward-only migration path.

``TrainingGoal.injury_severity`` is persisted as the closed-ontology
``InjurySeverity`` enum declared in
``docs/architecture/00-foundations/terminology.md → Shared Enums``,
stored as ``native_enum=False`` to match the rest of the Phase-1.2
column types. The schema-only plan does not enforce the
``goal_type = 'recovery' ↔ injury_severity IS NOT NULL`` invariant;
that pairing is owned by the application layer.

Revision ID: 1b9e9026db1e
Revises: e7ffc8764335
Create Date: 2026-06-20 16:43:44.824872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b9e9026db1e'
down_revision: Union[str, None] = 'e7ffc8764335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('goal_type', sa.Enum('race_event', 'target_performance', 'fitness_improvement', 'maintenance', 'recovery', name='goal_type', native_enum=False, length=32), nullable=False),
    sa.Column('goal_event_type', sa.Enum('marathon', 'half_marathon', '10k', '5k', 'ultra', 'trail_race', 'custom', name='goal_event_type', native_enum=False, length=32), nullable=True),
    sa.Column('goal_event_name', sa.String(length=255), nullable=True),
    sa.Column('goal_event_date', sa.Date(), nullable=True),
    sa.Column('custom_distance_km', sa.Float(), nullable=True),
    sa.Column('goal_description', sa.Text(), nullable=True),
    sa.Column('weekly_volume_hours', sa.Float(), nullable=False),
    sa.Column('weekly_volume_km', sa.Float(), nullable=False),
    sa.Column('fitness_level', sa.Integer(), nullable=False),
    sa.Column('recent_injury', sa.Text(), nullable=True),
    sa.Column('injury_severity', sa.Enum('minor', 'moderate', 'major', name='injury_severity', native_enum=False, length=16), nullable=True),
    sa.Column('target_distance_km', sa.Float(), nullable=True),
    sa.Column('target_time_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'abandoned', name='training_goal_status', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('custom_distance_km IS NULL OR custom_distance_km > 0', name='ck_training_goals_custom_distance_positive'),
    sa.CheckConstraint('fitness_level >= 1 AND fitness_level <= 5', name='ck_training_goals_fitness_level_1_to_5'),
    sa.CheckConstraint('target_distance_km IS NULL OR target_distance_km > 0', name='ck_training_goals_target_distance_positive'),
    sa.CheckConstraint('target_time_minutes IS NULL OR target_time_minutes > 0', name='ck_training_goals_target_time_positive'),
    sa.CheckConstraint('weekly_volume_hours >= 0', name='ck_training_goals_weekly_volume_hours_non_negative'),
    sa.CheckConstraint('weekly_volume_km >= 0', name='ck_training_goals_weekly_volume_km_non_negative'),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_training_goals_athlete_active', 'training_goals', ['athlete_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_index('ix_training_goals_athlete_created', 'training_goals', ['athlete_id', 'created_at'], unique=False)
    op.create_table('secondary_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('training_goal_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('marathon', 'half_marathon', '10k', '5k', 'ultra', 'trail_race', 'custom', name='goal_event_type', native_enum=False, length=32), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.Enum('B', 'C', name='secondary_event_priority', native_enum=False, length=16), nullable=False),
    sa.ForeignKeyConstraint(['training_goal_id'], ['training_goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_secondary_events_goal', 'secondary_events', ['training_goal_id'], unique=False)
    op.create_index('ix_secondary_events_goal_date', 'secondary_events', ['training_goal_id', 'event_date'], unique=False)
    op.create_table('training_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('training_goal_id', sa.UUID(), nullable=False),
    sa.Column('twin_state_id', sa.UUID(), nullable=True),
    sa.Column('phases_summary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('phase_definitions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('weekly_distributions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.Enum('active', 'superseded', 'completed', name='training_plan_status', native_enum=False, length=16), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('strategic_rationale', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checkpoint_schedule', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['training_goal_id'], ['training_goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_training_plans_goal_status', 'training_plans', ['training_goal_id', 'status'], unique=False)
    op.create_index('ix_training_plans_twin_state', 'training_plans', ['twin_state_id'], unique=False)
    op.create_table('regeneration_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('training_goal_id', sa.UUID(), nullable=False),
    sa.Column('training_plan_id', sa.UUID(), nullable=True),
    sa.Column('proposed_date', sa.Date(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('trigger', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('proposed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending_confirmation', 'confirmed', 'declined', 'expired')", name='ck_regeneration_tasks_status_valid'),
    sa.ForeignKeyConstraint(['training_goal_id'], ['training_goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_plan_id'], ['training_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_regeneration_tasks_pending', 'regeneration_tasks', ['training_goal_id', 'status'], unique=False, postgresql_where=sa.text("status = 'pending_confirmation'"))
    op.create_table('weekly_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('training_plan_id', sa.UUID(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('adjusted_intent', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('synthesised', 'active', 'completed', name='weekly_plan_status', native_enum=False, length=16), nullable=False),
    sa.Column('sessions_completed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sessions_missed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sessions_skipped', sa.Integer(), server_default='0', nullable=False),
    sa.Column('accumulated_fatigue_delta', sa.Float(), server_default='0', nullable=False),
    sa.Column('doubles_days_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('week_starts_at', sa.Date(), nullable=False),
    sa.Column('week_ends_at', sa.Date(), nullable=False),
    sa.CheckConstraint('doubles_days_count >= 0', name='ck_weekly_plans_doubles_days_count_non_negative'),
    sa.CheckConstraint('sessions_completed >= 0 AND sessions_missed >= 0 AND sessions_skipped >= 0', name='ck_weekly_plans_session_counters_non_negative'),
    sa.CheckConstraint('week_number >= 1', name='ck_weekly_plans_week_number_positive'),
    sa.ForeignKeyConstraint(['training_plan_id'], ['training_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_plan_id', 'week_number', name='uq_weekly_plans_plan_week')
    )
    op.create_index('ix_weekly_plans_plan_status', 'weekly_plans', ['training_plan_id', 'status'], unique=False)
    op.create_table('planned_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('weekly_plan_id', sa.UUID(), nullable=False),
    sa.Column('training_plan_id', sa.UUID(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('phase_label', sa.Enum('aerobic_base', 'aerobic_foundation', 'aerobic_accumulation', 'aerobic_build', 'hill_phase', 'structural_tolerance', 'threshold_build', 'threshold_peak', 'threshold_consolidation', 'vo2max_development', 'vo2max_sharpening', 'special_endurance', 'specific_endurance', 'race_rehearsal', 'sharpening', 'taper', 'race_week', 'recovery', 'transition', 'rolling_block', 'base_building', 'threshold_development', 'race_specific', name='phase_label', native_enum=False, length=32), nullable=False),
    sa.Column('session_type', sa.Enum('rest', 'recovery_run', 'easy_run', 'long_run', 'medium_long_run', 'steady_state', 'tempo', 'threshold', 'vo2max', 'hill_repeats', 'fartlek', 'strides', 'drills_mobility', 'cross_training', 'test_session', 'optional_run', name='session_type', native_enum=False, length=32), nullable=False),
    sa.Column('intent_description', sa.String(length=512), nullable=False),
    sa.Column('approximate_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('checkpoint_type', sa.Enum('calibration', 'benchmark', 'race_simulation', 'secondary_race', 'progress_review', name='checkpoint_type', native_enum=False, length=32), nullable=True),
    sa.Column('checkpoint_metric', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('pending', 'generated', 'completed', 'skipped', 'missed', 'redistributed', name='planned_session_status', native_enum=False, length=32), nullable=False),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.Column('redistributed_to_date', sa.Date(), nullable=True),
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('session_slot', sa.Enum('am', 'pm', name='session_slot', native_enum=False, length=8), nullable=True),
    sa.Column('session_priority', sa.Enum('primary', 'secondary', name='session_priority', native_enum=False, length=16), nullable=False),
    sa.Column('block_id', sa.String(length=64), nullable=True),
    sa.Column('block_position', sa.String(length=16), nullable=True),
    sa.Column('block_session_count', sa.Integer(), nullable=True),
    sa.Column('is_suggested', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("block_position IS NULL OR block_position IN ('first', 'middle', 'last')", name='ck_planned_sessions_block_position_valid'),
    sa.CheckConstraint('approximate_duration_minutes > 0', name='ck_planned_sessions_duration_positive'),
    sa.CheckConstraint('week_number >= 1', name='ck_planned_sessions_week_number_positive'),
    sa.ForeignKeyConstraint(['training_plan_id'], ['training_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weekly_plan_id'], ['weekly_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('weekly_plan_id', 'target_date', 'session_slot', name='uq_planned_sessions_plan_date_slot')
    )
    op.create_index('ix_planned_sessions_plan_date', 'planned_sessions', ['weekly_plan_id', 'target_date'], unique=False)
    op.create_index('ix_planned_sessions_status', 'planned_sessions', ['status', 'target_date'], unique=False)
    op.create_index('ix_planned_sessions_training_plan_date_slot', 'planned_sessions', ['training_plan_id', 'target_date', 'session_slot'], unique=False)
    op.create_table('weekly_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('weekly_plan_id', sa.UUID(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('session_type', sa.Enum('rest', 'recovery_run', 'easy_run', 'long_run', 'medium_long_run', 'steady_state', 'tempo', 'threshold', 'vo2max', 'hill_repeats', 'fartlek', 'strides', 'drills_mobility', 'cross_training', 'test_session', 'optional_run', name='session_type', native_enum=False, length=32), nullable=False),
    sa.Column('intent_description', sa.String(length=512), nullable=False),
    sa.Column('approximate_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_checkpoint', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('checkpoint_type', sa.Enum('calibration', 'benchmark', 'race_simulation', 'secondary_race', 'progress_review', name='checkpoint_type', native_enum=False, length=32), nullable=True),
    sa.Column('checkpoint_metric', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('planned_session_id', sa.UUID(), nullable=True),
    sa.Column('block_id', sa.String(length=64), nullable=True),
    sa.Column('block_position', sa.String(length=16), nullable=True),
    sa.Column('block_session_count', sa.Integer(), nullable=True),
    sa.CheckConstraint("block_position IS NULL OR block_position IN ('first', 'middle', 'last')", name='ck_weekly_sessions_block_position_valid'),
    sa.CheckConstraint("status IN ('scheduled', 'completed', 'skipped', 'missed')", name='ck_weekly_sessions_status_valid'),
    sa.CheckConstraint('approximate_duration_minutes > 0', name='ck_weekly_sessions_duration_positive'),
    sa.ForeignKeyConstraint(['weekly_plan_id'], ['weekly_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planned_session_id')
    )
    op.create_index('ix_weekly_sessions_plan', 'weekly_sessions', ['weekly_plan_id'], unique=False)
    op.create_index('ix_weekly_sessions_plan_date', 'weekly_sessions', ['weekly_plan_id', 'target_date'], unique=False)
    op.create_table('checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('planned_session_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('calibration', 'benchmark', 'race_simulation', 'secondary_race', 'progress_review', name='checkpoint_type', native_enum=False, length=32), nullable=False),
    sa.Column('target_metric', sa.String(length=128), nullable=False),
    sa.Column('secondary_metrics', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('twin_update_expected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('replan_trigger', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'skipped', name='checkpoint_status', native_enum=False, length=16), nullable=False),
    sa.Column('metric_updated', sa.Boolean(), nullable=True),
    sa.Column('confidence_changed', sa.Boolean(), nullable=True),
    sa.Column('replan_triggered', sa.Boolean(), nullable=True),
    sa.Column('trajectory_status', sa.String(length=16), nullable=True),
    sa.Column('proposal', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('scheduled', 'completed', 'skipped')", name='ck_checkpoints_status_valid'),
    sa.CheckConstraint("trajectory_status IS NULL OR trajectory_status IN ('ahead', 'on_track', 'behind', 'at_risk')", name='ck_checkpoints_trajectory_status_valid'),
    sa.ForeignKeyConstraint(['planned_session_id'], ['planned_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planned_session_id')
    )
    op.create_index('ix_checkpoints_planned_session', 'checkpoints', ['planned_session_id'], unique=False)
    op.create_index('ix_checkpoints_type_status', 'checkpoints', ['type', 'status'], unique=False)
    op.create_index('ix_activities_planned_session', 'activities', ['planned_session_id'], unique=False)
    op.create_foreign_key(
        'fk_activities_planned_session',
        'activities',
        'planned_sessions',
        ['planned_session_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_activities_planned_session',
        'activities',
        type_='foreignkey',
    )
    op.drop_index('ix_activities_planned_session', table_name='activities')
    op.drop_index('ix_checkpoints_type_status', table_name='checkpoints')
    op.drop_index('ix_checkpoints_planned_session', table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index('ix_weekly_sessions_plan_date', table_name='weekly_sessions')
    op.drop_index('ix_weekly_sessions_plan', table_name='weekly_sessions')
    op.drop_table('weekly_sessions')
    op.drop_index('ix_planned_sessions_training_plan_date_slot', table_name='planned_sessions')
    op.drop_index('ix_planned_sessions_status', table_name='planned_sessions')
    op.drop_index('ix_planned_sessions_plan_date', table_name='planned_sessions')
    op.drop_table('planned_sessions')
    op.drop_index('ix_weekly_plans_plan_status', table_name='weekly_plans')
    op.drop_table('weekly_plans')
    op.drop_index('ix_regeneration_tasks_pending', table_name='regeneration_tasks', postgresql_where=sa.text("status = 'pending_confirmation'"))
    op.drop_table('regeneration_tasks')
    op.drop_index('ix_training_plans_twin_state', table_name='training_plans')
    op.drop_index('ix_training_plans_goal_status', table_name='training_plans')
    op.drop_table('training_plans')
    op.drop_index('ix_secondary_events_goal_date', table_name='secondary_events')
    op.drop_index('ix_secondary_events_goal', table_name='secondary_events')
    op.drop_table('secondary_events')
    op.drop_index('ix_training_goals_athlete_created', table_name='training_goals')
    op.drop_index('ix_training_goals_athlete_active', table_name='training_goals', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('training_goals')
    # ### end Alembic commands ###
