"""phase_2_3_p3_drop_twin_states_activity_unique

Revision ID: 21f955c743cb
Revises: 8413e6547a40
Create Date: 2026-07-15 15:46:59.962131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21f955c743cb'
down_revision: Union[str, None] = '8413e6547a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_twin_states_athlete_activity'), table_name='twin_states', postgresql_where='(activity_id IS NOT NULL)')
    op.create_index('ix_twin_states_athlete_activity', 'twin_states', ['athlete_id', 'activity_id'], unique=False, postgresql_where=sa.text('activity_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_twin_states_athlete_activity', table_name='twin_states', postgresql_where=sa.text('activity_id IS NOT NULL'))
    op.create_index(op.f('uq_twin_states_athlete_activity'), 'twin_states', ['athlete_id', 'activity_id'], unique=True, postgresql_where='(activity_id IS NOT NULL)')
    # ### end Alembic commands ###
