"""phase_2_1_p3_sport_type_filtering

Revision ID: 2340974caeca
Revises: d1579f4430e7
Create Date: 2026-07-03 00:29:15.255934

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2340974caeca"
down_revision: Union[str, None] = "d1579f4430e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activities",
        sa.Column(
            "sport_type",
            sa.Enum(
                "running",
                "cycling",
                "swimming",
                "strength",
                "yoga_mobility",
                "other",
                "unknown",
                name="sport_type",
                native_enum=False,
                length=32,
            ),
            server_default="unknown",
            nullable=False,
        ),
    )
    op.add_column(
        "activities",
        sa.Column("sport_type_detection_version", sa.String(length=16), nullable=True),
    )
    op.add_column(
        "activities",
        sa.Column("has_gps", sa.Boolean(), server_default="false", nullable=False),
    )
    op.create_index(
        "ix_activities_athlete_calibration_eligible",
        "activities",
        ["athlete_id", "activity_date"],
        unique=False,
        postgresql_where=sa.text("calibration_eligible = true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_activities_athlete_calibration_eligible",
        table_name="activities",
        postgresql_where=sa.text("calibration_eligible = true"),
    )
    op.drop_column("activities", "has_gps")
    op.drop_column("activities", "sport_type_detection_version")
    op.drop_column("activities", "sport_type")
    # ### end Alembic commands ###
