"""add_planned_workout_id_and_notes_to_activity

Revision ID: 25743a77ba54
Revises: b6c3c84ae31d
Create Date: 2026-05-10 23:38:24.486953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25743a77ba54'
down_revision: Union[str, None] = 'b6c3c84ae31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('planned_workout_id', sa.UUID(), nullable=True))
    op.add_column('activities', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'notes')
    op.drop_column('activities', 'planned_workout_id')
    # ### end Alembic commands ###
