"""add coach_messages table

Revision ID: 27f66963d6eb
Revises: 31ac233877fe
Create Date: 2026-05-19 22:20:44.757301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27f66963d6eb'
down_revision: Union[str, None] = '31ac233877fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('twin_state_id', sa.UUID(), nullable=True),
    sa.Column('training_block_id', sa.UUID(), nullable=True),
    sa.Column('message_type', sa.Enum('FIRST_MESSAGE', 'DAILY_BRIEFING', 'POST_WORKOUT', 'WEEKLY_REVIEW', 'RECOVERY_ALERT', 'PHASE_TRANSITION', name='messagetype', native_enum=False, length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('generation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_block_id'], ['training_blocks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['twin_state_id'], ['twin_states.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_coach_messages_athlete_created_at', 'coach_messages', ['athlete_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_coach_messages_athlete_id'), 'coach_messages', ['athlete_id'], unique=False)
    op.create_index('ix_coach_messages_athlete_type', 'coach_messages', ['athlete_id', 'message_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_coach_messages_athlete_type', table_name='coach_messages')
    op.drop_index(op.f('ix_coach_messages_athlete_id'), table_name='coach_messages')
    op.drop_index('ix_coach_messages_athlete_created_at', table_name='coach_messages')
    op.drop_table('coach_messages')
    # ### end Alembic commands ###
