"""phase-2-2-p1-batch-1 raw-sensor-streams

Revision ID: 297ea8ac7f69
Revises: 2340974caeca
Create Date: 2026-07-07 23:48:46.385033

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "297ea8ac7f69"
down_revision: Union[str, None] = "2340974caeca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raw_sensor_streams",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("activity_id", sa.UUID(), nullable=False),
        sa.Column("fit_file_key", sa.String(length=512), nullable=False),
        sa.Column("sampling_rate_hz", sa.Float(), server_default="1.0", nullable=False),
        sa.Column(
            "available_channels",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("cleaning_pipeline_version", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["activity_id"], ["activities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("activity_id", name="uq_raw_sensor_streams_activity"),
    )
    op.create_index(
        "ix_raw_sensor_streams_activity",
        "raw_sensor_streams",
        ["activity_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_raw_sensor_streams_activity", table_name="raw_sensor_streams")
    op.drop_table("raw_sensor_streams")
    # ### end Alembic commands ###
