"""phase1c_twin_initialisation_v2

Revision ID: 31ac233877fe
Revises: 681ac990e655
Create Date: 2026-05-18 21:34:22.595010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31ac233877fe'
down_revision: Union[str, None] = '681ac990e655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twin_states',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('athlete_preferences_id', sa.UUID(), nullable=False),
    sa.Column('trigger', sa.Enum('QUESTIONNAIRE', 'CALIBRATION', 'WELLNESS_UPDATE', name='twintrigger', native_enum=False, length=30), nullable=False),
    sa.Column('confidence_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='confidencelevel', native_enum=False, length=10), nullable=False),
    sa.Column('data_tier', sa.Enum('TIER1', 'TIER2', 'TIER3', 'TIER4', 'TIER5', name='datatier', native_enum=False, length=10), nullable=False),
    sa.Column('fitness_score', sa.Float(), nullable=False),
    sa.Column('fatigue_score', sa.Float(), nullable=False),
    sa.Column('max_hr_estimate', sa.Float(), nullable=False),
    sa.Column('lt1_hr_estimate', sa.Float(), nullable=False),
    sa.Column('lt2_hr_estimate', sa.Float(), nullable=False),
    sa.Column('lt1_pace_estimate', sa.Float(), nullable=True),
    sa.Column('lt2_pace_estimate', sa.Float(), nullable=True),
    sa.Column('structural_capacity_score', sa.Float(), nullable=False),
    sa.Column('fitness_time_constant', sa.Float(), nullable=False),
    sa.Column('fatigue_time_constant', sa.Float(), nullable=False),
    sa.Column('computation_summary', sa.Text(), nullable=False),
    sa.Column('computation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fatigue_score >= 0', name='ck_twin_states_fatigue_non_negative'),
    sa.CheckConstraint('fitness_score >= 0 AND fitness_score <= 100', name='ck_twin_states_fitness_score_range'),
    sa.CheckConstraint('max_hr_estimate >= 140 AND max_hr_estimate <= 220', name='ck_twin_states_max_hr_range'),
    sa.CheckConstraint('structural_capacity_score >= 0 AND structural_capacity_score <= 1', name='ck_twin_states_structural_capacity_range'),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['athlete_preferences_id'], ['athlete_preferences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twin_states_athlete_id'), 'twin_states', ['athlete_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_twin_states_athlete_id'), table_name='twin_states')
    op.drop_table('twin_states')
    # ### end Alembic commands ###
