"""type-enforcement-audit-promote-inline-unions-to-saenum

Revision ID: 32fecd884e8e
Revises: 21f955c743cb
Create Date: 2026-07-24 23:25:19.686205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32fecd884e8e'
down_revision: Union[str, None] = '21f955c743cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('regeneration_tasks', 'trigger',
               existing_type=sa.TEXT(),
               type_=sa.Enum('trajectory_ahead', 'trajectory_at_risk', 'coach_conversation', name='regeneration_trigger', native_enum=False, length=32),
               existing_nullable=False)
    op.alter_column('regeneration_tasks', 'status',
               existing_type=sa.TEXT(),
               type_=sa.Enum('pending_confirmation', 'confirmed', 'declined', 'expired', name='regeneration_task_status', native_enum=False, length=32),
               existing_nullable=False)
    op.alter_column('weekly_sessions', 'status',
               existing_type=sa.TEXT(),
               type_=sa.Enum('scheduled', 'completed', 'skipped', 'missed', name='weekly_session_status', native_enum=False, length=16),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weekly_sessions', 'status',
               existing_type=sa.Enum('scheduled', 'completed', 'skipped', 'missed', name='weekly_session_status', native_enum=False, length=16),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('regeneration_tasks', 'status',
               existing_type=sa.Enum('pending_confirmation', 'confirmed', 'declined', 'expired', name='regeneration_task_status', native_enum=False, length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('regeneration_tasks', 'trigger',
               existing_type=sa.Enum('trajectory_ahead', 'trajectory_at_risk', 'coach_conversation', name='regeneration_trigger', native_enum=False, length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
