"""add_training_preferences_table

Revision ID: 528030ae164d
Revises: 25743a77ba54
Create Date: 2026-05-12 22:25:25.538471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '528030ae164d'
down_revision: Union[str, None] = '25743a77ba54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_preferences',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('goal_type', sa.Enum('RACE', 'FITNESS_IMPROVEMENT', 'MAINTENANCE', 'RECOVERY', name='goaltype', native_enum=False, length=20), nullable=True),
    sa.Column('goal_event_type', sa.Enum('K5', 'K10', 'HALF_MARATHON', 'MARATHON', 'ULTRA', 'CUSTOM', name='goaleventtype', native_enum=False, length=20), nullable=True),
    sa.Column('custom_distance_km', sa.Float(), nullable=True),
    sa.Column('goal_event_date', sa.Date(), nullable=True),
    sa.Column('goal_description', sa.String(length=500), nullable=True),
    sa.Column('weekly_volume_hours', sa.Float(), nullable=True),
    sa.Column('weekly_volume_km', sa.Float(), nullable=True),
    sa.Column('years_structured_training', sa.Float(), nullable=True),
    sa.Column('sport_background', sa.Enum('RUNNING_PRIMARY', 'CYCLING_CROSSOVER', 'SWIMMING_CROSSOVER', 'MULTI_SPORT', 'OTHER', name='sportbackground', native_enum=False, length=20), nullable=True),
    sa.Column('recent_injury', sa.Boolean(), nullable=True),
    sa.Column('weekly_schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gps_source', sa.Enum('NONE', 'PHONE', 'WATCH', name='gpssource', native_enum=False, length=20), nullable=True),
    sa.Column('hr_source', sa.Enum('NONE', 'WRIST_OPTICAL', 'CHEST_STRAP', name='hrsource', native_enum=False, length=20), nullable=True),
    sa.Column('power_source', sa.Enum('NONE', 'RUNNING_POWER', name='powersource', native_enum=False, length=20), nullable=True),
    sa.Column('primary_training_platform', sa.Enum('UNKNOWN', 'GARMIN_CONNECT', 'COROS', 'POLAR_FLOW', 'SUUNTO', 'INTERVALS_ICU', 'STRAVA', 'TRAININGPEAKS', 'OTHER', name='primarytrainingplatform', native_enum=False, length=20), nullable=True),
    sa.Column('fitness_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_training_preferences_athlete_created_at', 'training_preferences', ['athlete_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_training_preferences_athlete_id'), 'training_preferences', ['athlete_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_preferences_athlete_id'), table_name='training_preferences')
    op.drop_index('ix_training_preferences_athlete_created_at', table_name='training_preferences')
    op.drop_table('training_preferences')
    # ### end Alembic commands ###
