"""add onboarding complete to athletes

Revision ID: 681ac990e655
Revises: 7a2b1c3d4e5f
Create Date: 2026-05-15 00:32:22.703132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '681ac990e655'
down_revision: Union[str, None] = '7a2b1c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athletes', sa.Column('onboarding_complete', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('athletes', 'onboarding_complete')
    # ### end Alembic commands ###
