"""add_athlete_fitness_table

Revision ID: 76e28f218e05
Revises: 34a49b0915d6
Create Date: 2026-05-08 00:05:57.537257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76e28f218e05'
down_revision: Union[str, None] = '16dd8b55b1ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.create_table('athlete_fitness',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('tss', sa.Float(), nullable=True),
    sa.Column('atl', sa.Float(), nullable=True),
    sa.Column('ctl', sa.Float(), nullable=True),
    sa.Column('tsb', sa.Float(), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'GARMIN', 'WHOOP', 'OURA', 'POLAR', name='wellnesssource', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('athlete_id', 'metric_date'),
    sa.UniqueConstraint('athlete_id', 'metric_date', name='uq_athlete_fitness_date')
    )
    op.create_index(op.f('ix_athlete_fitness_athlete_id'), 'athlete_fitness', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_athlete_fitness_metric_date'), 'athlete_fitness', ['metric_date'], unique=False)
    op.execute("SELECT create_hypertable('athlete_fitness', 'metric_date', if_not_exists => TRUE);")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("SELECT drop_hypertable('athlete_fitness', if_exists => TRUE, cascade => TRUE);")
    op.drop_index(op.f('ix_athlete_fitness_metric_date'), table_name='athlete_fitness')
    op.drop_index(op.f('ix_athlete_fitness_athlete_id'), table_name='athlete_fitness')
    op.drop_table('athlete_fitness')
    # ### end Alembic commands ###
