"""phase_1_2c_twin_fitness_coaching_workouts

Revision ID: 79dc97d4e433
Revises: 1b9e9026db1e
Create Date: 2026-06-24 12:39:31.253309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79dc97d4e433'
down_revision: Union[str, None] = '1b9e9026db1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete_physiology',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('lt1', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lt2', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cp', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vo2max', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_hr', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_athlete_physiology_athlete', 'athlete_physiology', ['athlete_id'], unique=True)
    op.create_table('generation_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=96), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('trigger_context', sa.Text(), nullable=False),
    sa.Column('input_token_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_token_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('latency_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('success', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(success = TRUE AND failure_reason IS NULL) OR (success = FALSE AND failure_reason IS NOT NULL)', name='ck_generation_events_failure_reason_consistency'),
    sa.CheckConstraint('input_token_count >= 0 AND output_token_count >= 0', name='ck_generation_events_token_counts_non_negative'),
    sa.CheckConstraint('latency_ms >= 0', name='ck_generation_events_latency_non_negative'),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generation_events_agent_at', 'generation_events', ['agent_name', 'created_at'], unique=False)
    op.create_index('ix_generation_events_athlete_at', 'generation_events', ['athlete_id', 'created_at'], unique=False)
    op.create_index('ix_generation_events_success_at', 'generation_events', ['success', 'created_at'], unique=False)
    op.create_table('athlete_fitness',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('aggregate', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('aerobic', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('neuromuscular', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('structural', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('time_constants', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_activity_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(aerobic IS NULL) OR ((aerobic->>'form')::float = (aerobic->>'fitness')::float - (aerobic->>'fatigue')::float)", name='ck_athlete_fitness_aerobic_form_invariant'),
    sa.CheckConstraint("(aggregate->>'form')::float = (aggregate->>'fitness')::float - (aggregate->>'fatigue')::float", name='ck_athlete_fitness_aggregate_form_invariant'),
    sa.CheckConstraint("(neuromuscular IS NULL) OR ((neuromuscular->>'form')::float = (neuromuscular->>'fitness')::float - (neuromuscular->>'fatigue')::float)", name='ck_athlete_fitness_neuromuscular_form_invariant'),
    sa.CheckConstraint("(structural IS NULL) OR ((structural->>'form')::float = (structural->>'fitness')::float - (structural->>'fatigue')::float)", name='ck_athlete_fitness_structural_form_invariant'),
    sa.CheckConstraint("(time_constants->>'source') IN ('population_default', 'individual_fitted')", name='ck_athlete_fitness_time_constants_source_valid'),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_activity_id'], ['activities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_athlete_fitness_last_activity', 'athlete_fitness', ['last_activity_id'], unique=False)
    op.create_index('uq_athlete_fitness_athlete', 'athlete_fitness', ['athlete_id'], unique=True)
    op.create_table('twin_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('training_goal_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('data_tier', sa.Integer(), nullable=False),
    sa.Column('confidence_level', sa.Enum('low', 'medium', 'high', name='twin_confidence_level', native_enum=False, length=16), nullable=False),
    sa.Column('trigger', sa.Enum('questionnaire', 'activity_sync', 'calibration', 'physiology_input', 'wellness_update', name='twin_trigger', native_enum=False, length=32), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fitness', sa.Float(), nullable=False),
    sa.Column('fatigue', sa.Float(), nullable=False),
    sa.Column('form', sa.Float(), nullable=False),
    sa.Column('lt1_pace_sec_per_km', sa.Float(), nullable=True),
    sa.Column('lt1_power_watts', sa.Float(), nullable=True),
    sa.Column('lt1_hr_bpm', sa.Float(), nullable=True),
    sa.Column('lt2_pace_sec_per_km', sa.Float(), nullable=True),
    sa.Column('lt2_power_watts', sa.Float(), nullable=True),
    sa.Column('lt2_hr_bpm', sa.Float(), nullable=True),
    sa.Column('cp_watts', sa.Float(), nullable=True),
    sa.Column('readiness_level', sa.Enum('green', 'amber', 'red', name='recovery_modifier_level', native_enum=False, length=8), nullable=False),
    sa.Column('wellness_trend', sa.Enum('improving', 'stable', 'declining', name='wellness_trend', native_enum=False, length=16), nullable=True),
    sa.Column('metric_confidence', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_goal_id'], ['training_goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_twin_states_latest', 'twin_states', ['athlete_id', 'created_at'], unique=False)
    op.create_index('ix_twin_states_activity', 'twin_states', ['activity_id'], unique=False)
    op.create_index('ix_twin_states_training_goal', 'twin_states', ['training_goal_id'], unique=False)
    op.create_index('uq_twin_states_athlete_activity', 'twin_states', ['athlete_id', 'activity_id'], unique=True, postgresql_where=sa.text('activity_id IS NOT NULL'))
    op.create_table('coaching_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('twin_state_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('message_type', sa.Enum('first_message', 'post_workout', 'wellness_alert', 'phase_transition', 'plan_regeneration', 'confidence_upgrade', 'cycle_check_in', 'weekly_summary', name='message_type', native_enum=False, length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(content) > 0', name='ck_coaching_messages_content_non_empty'),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['twin_state_id'], ['twin_states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_coaching_messages_athlete_generated_at', 'coaching_messages', ['athlete_id', 'generated_at'], unique=False)
    op.create_index('ix_coaching_messages_athlete_type_generated_at', 'coaching_messages', ['athlete_id', 'message_type', 'generated_at'], unique=False)
    op.create_index('ix_coaching_messages_twin_state', 'coaching_messages', ['twin_state_id'], unique=False)
    op.create_index('uq_coaching_messages_activity_post_workout', 'coaching_messages', ['activity_id'], unique=True, postgresql_where="message_type = 'post_workout' AND activity_id IS NOT NULL")
    op.create_index('uq_coaching_messages_athlete_first_message', 'coaching_messages', ['athlete_id'], unique=True, postgresql_where=sa.text("message_type = 'first_message'"))
    op.create_table('generated_workouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('planned_session_id', sa.UUID(), nullable=False),
    sa.Column('twin_state_id', sa.UUID(), nullable=False),
    sa.Column('theoretical_targets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('adjusted_targets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recovery_modifier_level', sa.Enum('green', 'amber', 'red', name='recovery_modifier_level', native_enum=False, length=8), server_default='green', nullable=False),
    sa.Column('recovery_modifier_reason', sa.Text(), nullable=True),
    sa.Column('generation_date', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(theoretical_targets) = 'object' AND jsonb_typeof(adjusted_targets) = 'object'", name='ck_generated_workouts_targets_are_objects'),
    sa.CheckConstraint("recovery_modifier_level IN ('green', 'amber', 'red')", name='ck_generated_workouts_recovery_modifier_level_valid'),
    sa.ForeignKeyConstraint(['planned_session_id'], ['planned_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['twin_state_id'], ['twin_states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planned_session_id', 'generation_date', name='uq_generated_workouts_planned_session_generation_date')
    )
    op.create_index('ix_generated_workouts_planned_session_generated', 'generated_workouts', ['planned_session_id', 'generated_at'], unique=False)
    op.create_index('ix_generated_workouts_twin_state', 'generated_workouts', ['twin_state_id'], unique=False)
    op.create_table('workout_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('generated_workout_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.Enum('warmup', 'work', 'recovery', 'cooldown', name='step_type', native_enum=False, length=16), nullable=False),
    sa.Column('session_type', sa.Enum('rest', 'recovery_run', 'easy_run', 'long_run', 'medium_long_run', 'steady_state', 'tempo', 'threshold', 'vo2max', 'hill_repeats', 'fartlek', 'strides', 'drills_mobility', 'cross_training', 'test_session', 'optional_run', name='session_type', native_enum=False, length=32), nullable=False),
    sa.Column('physiological_intent', sa.Enum('low_aerobic', 'high_aerobic', 'threshold', 'vo2max', 'neuromuscular', 'recovery', name='physiological_intent', native_enum=False, length=32), nullable=False),
    sa.Column('session_purpose', sa.Enum('general', 'race_specific', 'calibration', name='session_purpose', native_enum=False, length=16), server_default='general', nullable=False),
    sa.Column('target', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds >= 0', name='ck_workout_steps_duration_non_negative'),
    sa.CheckConstraint('length(description) > 0', name='ck_workout_steps_description_non_empty'),
    sa.CheckConstraint('step_order >= 1', name='ck_workout_steps_step_order_positive'),
    sa.ForeignKeyConstraint(['generated_workout_id'], ['generated_workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generated_workout_id', 'step_order', name='uq_workout_steps_generated_workout_step_order')
    )
    op.create_index('ix_workout_steps_generated_workout_order', 'workout_steps', ['generated_workout_id', 'step_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workout_steps_generated_workout_order', table_name='workout_steps')
    op.drop_table('workout_steps')
    op.drop_index('ix_generated_workouts_twin_state', table_name='generated_workouts')
    op.drop_index('ix_generated_workouts_planned_session_generated', table_name='generated_workouts')
    op.drop_table('generated_workouts')
    op.drop_index('uq_coaching_messages_athlete_first_message', table_name='coaching_messages', postgresql_where=sa.text("message_type = 'first_message'"))
    op.drop_index('uq_coaching_messages_activity_post_workout', table_name='coaching_messages', postgresql_where="message_type = 'post_workout' AND activity_id IS NOT NULL")
    op.drop_index('ix_coaching_messages_twin_state', table_name='coaching_messages')
    op.drop_index('ix_coaching_messages_athlete_type_generated_at', table_name='coaching_messages')
    op.drop_index('ix_coaching_messages_athlete_generated_at', table_name='coaching_messages')
    op.drop_table('coaching_messages')
    op.drop_index('uq_twin_states_athlete_activity', table_name='twin_states', postgresql_where=sa.text('activity_id IS NOT NULL'))
    op.drop_index('ix_twin_states_training_goal', table_name='twin_states')
    op.drop_index('ix_twin_states_activity', table_name='twin_states')
    op.drop_index('idx_twin_states_latest', table_name='twin_states')
    op.drop_table('twin_states')
    op.drop_index('uq_athlete_fitness_athlete', table_name='athlete_fitness')
    op.drop_index('ix_athlete_fitness_last_activity', table_name='athlete_fitness')
    op.drop_table('athlete_fitness')
    op.drop_index('ix_generation_events_success_at', table_name='generation_events')
    op.drop_index('ix_generation_events_athlete_at', table_name='generation_events')
    op.drop_index('ix_generation_events_agent_at', table_name='generation_events')
    op.drop_table('generation_events')
    op.drop_index('uq_athlete_physiology_athlete', table_name='athlete_physiology')
    op.drop_table('athlete_physiology')
    # ### end Alembic commands ###
