"""phase_1_1_p3_single_primary_auth_enforcement

Revision ID: 8265efd46112
Revises: fd373abd4b9e
Create Date: 2026-06-17 14:20:32.859975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8265efd46112'
down_revision: Union[str, None] = 'fd373abd4b9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_athlete_auths_single_primary', 'athlete_auths', ['athlete_id'], unique=True, postgresql_where=sa.text('is_primary = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_athlete_auths_single_primary', table_name='athlete_auths', postgresql_where=sa.text('is_primary = true'))
    # ### end Alembic commands ###
