"""phase_2_3_p1_physiology_measurement

Revision ID: 8413e6547a40
Revises: 84d65f756e09
Create Date: 2026-07-10 22:03:13.948542

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8413e6547a40"
down_revision: Union[str, None] = "84d65f756e09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create physiology_measurements table.

    NOTE: procrastinate_* tables (procrastinate_jobs, procrastinate_events,
    procrastinate_periodic_defers) are managed by procrastinate itself via
    ``procrastinate schema --install``, NOT by Alembic. The ``include_object``
    filter in ``alembic/env.py`` excludes them from autogenerate, so they do
    not appear in this or any future migration.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "physiology_measurements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("activity_id", sa.UUID(), nullable=True),
        sa.Column(
            "parameter",
            sa.Enum(
                "lt1_hr",
                "lt1_power",
                "lt1_pace",
                "lt2_hr",
                "lt2_power",
                "lt2_pace",
                "cp",
                "vo2max_ml_kg_min",
                "vo2max_power",
                "max_hr",
                name="physiology_parameter",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("observed_value", sa.Float(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "questionnaire_estimate",
                "training_hr_deflection",
                "training_rr_inflection",
                "training_power_hr_ratio",
                "field_test",
                "lab_test",
                name="measurement_source",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("measurement_date", sa.Date(), nullable=False),
        sa.Column("algorithm_used", sa.String(length=64), nullable=True),
        sa.Column("confidence_weight", sa.Float(), nullable=True),
        sa.Column("raw_data_reference", sa.String(length=512), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"], ["activities.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["athlete_id"], ["athletes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_physiology_measurements_athlete_date",
        "physiology_measurements",
        ["athlete_id", "measurement_date"],
        unique=False,
    )
    op.create_index(
        "ix_physiology_measurements_athlete_parameter_source",
        "physiology_measurements",
        ["athlete_id", "parameter", "source"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_physiology_measurements_athlete_parameter_source",
        table_name="physiology_measurements",
    )
    op.drop_index(
        "ix_physiology_measurements_athlete_date", table_name="physiology_measurements"
    )
    op.drop_table("physiology_measurements")
    # ### end Alembic commands ###
