"""widen cleaning_pipeline_version columns to 32 chars

Revision ID: 84d65f756e09
Revises: 297ea8ac7f69
Create Date: 2026-07-09 23:41:10.261583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d65f756e09'
down_revision: Union[str, None] = '297ea8ac7f69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'cleaning_pipeline_version',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('raw_sensor_streams', 'cleaning_pipeline_version',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_sensor_streams', 'cleaning_pipeline_version',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.alter_column('activities', 'cleaning_pipeline_version',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    # ### end Alembic commands ###
