"""phase_1e_training_plan_generation

Revision ID: 8579bb2791bc
Revises: 27f66963d6eb
Create Date: 2026-05-20 21:41:42.681576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8579bb2791bc'
down_revision: Union[str, None] = '27f66963d6eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_plans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('training_block_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='trainingplanstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generation_metadata', sa.JSON(), nullable=False),
    sa.Column('plan_rationale', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_block_id'], ['training_blocks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_training_plans_active_per_athlete', 'training_plans', ['athlete_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_index('ix_training_plans_athlete_created_at', 'training_plans', ['athlete_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_training_plans_athlete_id'), 'training_plans', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_training_plans_training_block_id'), 'training_plans', ['training_block_id'], unique=False)
    op.create_table('planned_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('training_plan_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('session_type', sa.Enum('REST', 'RECOVERY_RUN', 'EASY_RUN', 'LONG_RUN', 'MEDIUM_LONG_RUN', 'STEADY_STATE', 'TEMPO', 'THRESHOLD', 'VO2MAX', 'HILL_REPEATS', 'FARTLEK', 'RACE_SPECIFIC', 'STRIDES', 'DRILLS_MOBILITY', 'CROSS_TRAINING', 'TEST_SESSION', 'OPTIONAL_RUN', name='sessiontype', native_enum=False, length=30), nullable=False),
    sa.Column('dominant_physiological_intent', sa.Enum('LOW_AEROBIC', 'HIGH_AEROBIC', 'THRESHOLD', 'VO2MAX', 'RACE_SPECIFIC', 'NEUROMUSCULAR', 'RECOVERY_SUPPORT', 'CALIBRATION', name='physiologicalintent', native_enum=False, length=30), nullable=False),
    sa.Column('target_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_key_session', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Enum('BASE', 'BUILD', 'PEAK', 'TAPER', 'RACE', 'RECOVERY', name='trainingphase', native_enum=False, length=20), nullable=False),
    sa.Column('generation_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['training_plan_id'], ['training_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_planned_sessions_plan_date', 'planned_sessions', ['training_plan_id', 'scheduled_date'], unique=False)
    op.create_index('ix_planned_sessions_plan_week', 'planned_sessions', ['training_plan_id', 'week_number'], unique=False)
    op.create_index(op.f('ix_planned_sessions_training_plan_id'), 'planned_sessions', ['training_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_planned_sessions_training_plan_id'), table_name='planned_sessions')
    op.drop_index('ix_planned_sessions_plan_week', table_name='planned_sessions')
    op.drop_index('ix_planned_sessions_plan_date', table_name='planned_sessions')
    op.drop_table('planned_sessions')
    op.drop_index(op.f('ix_training_plans_training_block_id'), table_name='training_plans')
    op.drop_index(op.f('ix_training_plans_athlete_id'), table_name='training_plans')
    op.drop_index('ix_training_plans_athlete_created_at', table_name='training_plans')
    op.drop_index('ix_training_plans_active_per_athlete', table_name='training_plans', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('training_plans')
    # ### end Alembic commands ###
