"""alter_athlete_profile_country_language

Revision ID: b6c3c84ae31d
Revises: 7107ac5cb44f
Create Date: 2026-05-10 22:54:01.643277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6c3c84ae31d'
down_revision: Union[str, None] = '7107ac5cb44f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('athlete_profiles', 'country_code',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('athlete_profiles', 'country_code',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
    # ### end Alembic commands ###
