"""add_training_plans_twin_state_fk

Revision ID: d1579f4430e7
Revises: 79dc97d4e433
Create Date: 2026-06-24 16:32:28.155989

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d1579f4430e7"
down_revision: Union[str, None] = "79dc97d4e433"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_training_plans_twin_state",
        "training_plans",
        "twin_states",
        ["twin_state_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_training_plans_twin_state", "training_plans", type_="foreignkey"
    )
    # ### end Alembic commands ###
