"""phase_1_2a_profile_preferences_activity

Revision ID: e7ffc8764335
Revises: 8265efd46112
Create Date: 2026-06-19 22:06:37.655736

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e7ffc8764335"
down_revision: Union[str, None] = "8265efd46112"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("planned_session_id", sa.UUID(), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "intervals_icu",
                "manual_upload",
                "garmin_direct",
                "manual_entry",
                name="activity_source",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("external_id", sa.String(length=128), nullable=True),
        sa.Column("activity_date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("aerobic_load", sa.Float(), nullable=True),
        sa.Column("neuromuscular_load", sa.Float(), nullable=True),
        sa.Column("structural_load", sa.Float(), nullable=True),
        sa.Column("has_hr", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "has_rr_intervals", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("has_power", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "calibration_eligible", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "quality_flags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("fit_file_key", sa.String(length=512), nullable=True),
        sa.Column("ingestion_pipeline_version", sa.String(length=16), nullable=True),
        sa.Column("cleaning_pipeline_version", sa.String(length=16), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["athlete_id"], ["athletes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_activities_athlete_date",
        "activities",
        ["athlete_id", "activity_date"],
        unique=False,
    )
    op.create_index(
        "ix_activities_athlete_start_time",
        "activities",
        ["athlete_id", "start_time"],
        unique=False,
    )
    op.create_index(
        "uq_activities_athlete_external_source",
        "activities",
        ["athlete_id", "external_id", "source"],
        unique=True,
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )
    op.create_table(
        "athlete_preferences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column(
            "sport_background",
            sa.Enum(
                "running_primary",
                "cycling",
                "swimming",
                "triathlon",
                "team_sport",
                "gym_fitness",
                "none",
                name="sport_background",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("years_structured_training", sa.Integer(), nullable=False),
        sa.Column(
            "training_time_of_day",
            sa.Enum(
                "morning",
                "afternoon",
                "evening",
                "variable",
                name="training_time_of_day",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "weekly_schedule", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "gps_source",
            sa.Enum(
                "garmin_watch",
                "apple_watch",
                "polar",
                "suunto",
                "coros",
                "other",
                name="gps_source",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "hr_source",
            sa.Enum(
                "chest_strap_rr",
                "chest_strap_no_rr",
                "wrist_optical",
                "none",
                name="hr_source",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "power_source",
            sa.Enum(
                "running_power_meter",
                "none",
                name="power_source",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "primary_training_platform",
            sa.Enum(
                "intervals_icu",
                "garmin_connect",
                "manual",
                name="primary_training_platform",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "years_structured_training >= 0",
            name="ck_athlete_preferences_years_structured_training_non_negative",
        ),
        sa.ForeignKeyConstraint(["athlete_id"], ["athletes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id"),
    )
    op.add_column(
        "athlete_profiles",
        sa.Column(
            "gap_curve_model", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "athlete_profiles",
        sa.Column(
            "weather_response_model",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.add_column(
        "athlete_profiles",
        sa.Column(
            "banister_constants", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "athlete_profiles",
        sa.Column(
            "cycle_personal_model",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.add_column(
        "athlete_profiles",
        sa.Column("location_lat", sa.Numeric(precision=9, scale=6), nullable=True),
    )
    op.add_column(
        "athlete_profiles",
        sa.Column("location_lng", sa.Numeric(precision=9, scale=6), nullable=True),
    )
    op.add_column(
        "athlete_profiles", sa.Column("timezone", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "athlete_profiles",
        sa.Column(
            "training_window", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "athlete_profiles",
        sa.Column("current_effort_generation", sa.Integer(), nullable=True),
    )
    op.add_column(
        "athlete_profiles",
        sa.Column("structural_risk_flag", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "athlete_profiles",
        sa.Column(
            "objective_thresholds",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("athlete_profiles", "objective_thresholds")
    op.drop_column("athlete_profiles", "structural_risk_flag")
    op.drop_column("athlete_profiles", "current_effort_generation")
    op.drop_column("athlete_profiles", "training_window")
    op.drop_column("athlete_profiles", "timezone")
    op.drop_column("athlete_profiles", "location_lng")
    op.drop_column("athlete_profiles", "location_lat")
    op.drop_column("athlete_profiles", "cycle_personal_model")
    op.drop_column("athlete_profiles", "banister_constants")
    op.drop_column("athlete_profiles", "weather_response_model")
    op.drop_column("athlete_profiles", "gap_curve_model")
    op.drop_table("athlete_preferences")
    op.drop_index(
        "uq_activities_athlete_external_source",
        table_name="activities",
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )
    op.drop_index("ix_activities_athlete_start_time", table_name="activities")
    op.drop_index("ix_activities_athlete_date", table_name="activities")
    op.drop_table("activities")
    # ### end Alembic commands ###
