"""phase-1-1-email-password-auth

Revision ID: fd373abd4b9e
Revises:
Create Date: 2026-06-13 23:38:11.372112

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fd373abd4b9e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "athletes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column(
            "onboarding_complete", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_athletes_lower_email_unique",
        "athletes",
        [sa.literal_column("lower(email)")],
        unique=True,
    )
    op.create_table(
        "system_events",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=96), nullable=False),
        sa.Column("version", sa.String(length=16), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "produced_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        "ix_system_events_athlete_at",
        "system_events",
        ["athlete_id", "produced_at"],
        unique=False,
    )
    op.create_index(
        "ix_system_events_type_at",
        "system_events",
        ["event_type", "produced_at"],
        unique=False,
    )
    op.create_table(
        "athlete_auths",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "EMAIL",
                "GOOGLE",
                "STRAVA",
                name="auth_provider",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("provider_user_id", sa.String(length=255), nullable=True),
        sa.Column("hashed_password", sa.String(length=255), nullable=True),
        sa.Column(
            "provider_tokens", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("is_primary", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["athlete_id"], ["athletes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "athlete_id", "provider", name="uq_athlete_auths_athlete_id_provider"
        ),
    )
    op.create_index(
        "ix_athlete_auths_provider_user_id",
        "athlete_auths",
        ["provider_user_id"],
        unique=False,
    )
    op.create_table(
        "athlete_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column(
            "sex",
            sa.Enum(
                "MALE",
                "FEMALE",
                "NOT_SPECIFIED",
                name="sex",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("height_cm", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["athlete_id"], ["athletes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id"),
    )
    op.create_table(
        "athlete_refresh_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_refresh_token_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["athlete_id"], ["athletes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["replaced_by_refresh_token_id"],
            ["athlete_refresh_tokens.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        "ix_athlete_refresh_tokens_athlete_expires",
        "athlete_refresh_tokens",
        ["athlete_id", "expires_at"],
        unique=False,
    )
    op.create_table(
        "system_event_outbox",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PUBLISHED",
                "FAILED",
                "DLQ",
                name="event_publication_status",
                native_enum=False,
                length=16,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending','published','failed','dlq')",
            name="ck_system_event_outbox_status_valid",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["system_events.event_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        "ix_system_event_outbox_pending_failed",
        "system_event_outbox",
        ["created_at"],
        unique=False,
        postgresql_where="status IN ('pending', 'failed')",
    )
    op.create_index(
        "ix_system_event_outbox_status_created",
        "system_event_outbox",
        ["status", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_system_event_outbox_status_created", table_name="system_event_outbox"
    )
    op.drop_index(
        "ix_system_event_outbox_pending_failed",
        table_name="system_event_outbox",
        postgresql_where="status IN ('pending', 'failed')",
    )
    op.drop_table("system_event_outbox")
    op.drop_index(
        "ix_athlete_refresh_tokens_athlete_expires", table_name="athlete_refresh_tokens"
    )
    op.drop_table("athlete_refresh_tokens")
    op.drop_table("athlete_profiles")
    op.drop_index("ix_athlete_auths_provider_user_id", table_name="athlete_auths")
    op.drop_table("athlete_auths")
    op.drop_index("ix_system_events_type_at", table_name="system_events")
    op.drop_index("ix_system_events_athlete_at", table_name="system_events")
    op.drop_table("system_events")
    op.drop_index("ix_athletes_lower_email_unique", table_name="athletes")
    op.drop_table("athletes")
    # ### end Alembic commands ###
