"""Integration tests for Wellness model integrity and database constraints.

These tests verify that the AthleteWellness model correctly implements
database constraints, UUID defaults, and schema alignment.
"""

import uuid

import pytest
from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.athlete import Athlete
from app.models.enums import AthleteStatus, WellnessSource
from app.models.wellness import AthleteWellness
from app.repositories.athlete_repository import AthleteRepository


@pytest.fixture
async def athlete_in_db(test_db_session: AsyncSession) -> Athlete:
    """Create an athlete in the database for testing."""
    athlete_repo = AthleteRepository(test_db_session)
    athlete = await athlete_repo.create(
        id=uuid.uuid4(),
        email=f"test_{uuid.uuid4().hex[:8]}@example.com",
        hashed_password=None,
        status=AthleteStatus.ACTIVE,
    )
    return athlete


class TestWellnessUUIDDefault:
    """Tests for AthleteWellness UUID default."""

    @pytest.mark.asyncio
    async def test_wellness_record_generates_uuid_when_not_provided(
        self, test_db_session: AsyncSession, athlete_in_db: Athlete
    ):
        """Test that inserting a wellness record without id uses database gen_random_uuid()."""
        wellness = AthleteWellness(
            athlete_id=athlete_in_db.id,
            metric_date=__import__("datetime").date(2024, 1, 1),
            sleep_total=480,
            source=WellnessSource.MANUAL,
            timezone="UTC",
        )
        test_db_session.add(wellness)
        await test_db_session.commit()
        await test_db_session.refresh(wellness)

        # Verify UUID was generated by the database
        assert wellness.id is not None
        assert isinstance(wellness.id, uuid.UUID)


class TestWellnessUniqueConstraint:
    """Tests for AthleteWellness unique constraint on athlete_id + metric_date."""

    @pytest.mark.asyncio
    async def test_wellness_duplicate_athlete_date_raises_integrity_error(
        self, test_db_session: AsyncSession, athlete_in_db: Athlete
    ):
        """Test that inserting two wellness records with same athlete_id and metric_date raises IntegrityError."""
        from datetime import date

        # Create first wellness record
        wellness1 = AthleteWellness(
            athlete_id=athlete_in_db.id,
            metric_date=date(2024, 1, 1),
            sleep_total=480,
            source=WellnessSource.MANUAL,
            timezone="UTC",
        )
        test_db_session.add(wellness1)
        await test_db_session.commit()

        # Attempt to create second wellness record with same athlete_id and metric_date
        wellness2 = AthleteWellness(
            athlete_id=athlete_in_db.id,
            metric_date=date(2024, 1, 1),
            sleep_total=500,
            source=WellnessSource.MANUAL,
            timezone="UTC",
        )
        test_db_session.add(wellness2)

        with pytest.raises(IntegrityError):
            await test_db_session.commit()

    @pytest.mark.asyncio
    async def test_wellness_same_date_different_athletes_allowed(
        self, test_db_session: AsyncSession
    ):
        """Test that different athletes can have wellness records for the same date."""
        from datetime import date

        athlete_repo = AthleteRepository(test_db_session)

        athlete1 = await athlete_repo.create(
            id=uuid.uuid4(),
            email=f"test_{uuid.uuid4().hex[:8]}@example.com",
            hashed_password=None,
            status=AthleteStatus.ACTIVE,
        )

        athlete2 = await athlete_repo.create(
            id=uuid.uuid4(),
            email=f"test_{uuid.uuid4().hex[:8]}@example.com",
            hashed_password=None,
            status=AthleteStatus.ACTIVE,
        )

        # Create wellness records for both athletes on the same date
        wellness1 = AthleteWellness(
            athlete_id=athlete1.id,
            metric_date=date(2024, 1, 1),
            sleep_total=480,
            source=WellnessSource.MANUAL,
            timezone="UTC",
        )
        wellness2 = AthleteWellness(
            athlete_id=athlete2.id,
            metric_date=date(2024, 1, 1),
            sleep_total=500,
            source=WellnessSource.MANUAL,
            timezone="UTC",
        )

        test_db_session.add(wellness1)
        test_db_session.add(wellness2)
        await test_db_session.commit()

        # Both should succeed
        assert wellness1.id is not None
        assert wellness2.id is not None


class TestWellnessSchemaAlignment:
    """Tests for AthleteWellness ORM model schema alignment with database."""

    @pytest.mark.asyncio
    async def test_wellness_model_columns_match_expected_schema(self):
        """Test that AthleteWellness ORM model has all expected columns."""
        expected_columns = {
            "id",
            "athlete_id",
            "metric_date",
            "sleep_total",
            "sleep_light",
            "sleep_deep",
            "sleep_rem",
            "sleep_awake",
            "resting_hr",
            "hrv",
            "weight",
            "source",
            "timezone",
            "created_at",
            "updated_at",
        }

        actual_columns = {col.name for col in AthleteWellness.__table__.columns}

        assert expected_columns == actual_columns, (
            f"Column mismatch. Expected: {expected_columns}, Actual: {actual_columns}"
        )

    @pytest.mark.asyncio
    async def test_wellness_model_has_unique_constraint(self):
        """Test that AthleteWellness has unique constraint on athlete_id + metric_date."""
        table_args = AthleteWellness.__table_args__

        # Find the unique constraint
        unique_constraints = [
            arg for arg in table_args
            if arg.__class__.__name__ == "UniqueConstraint"
        ]

        assert len(unique_constraints) >= 1, "Expected at least one UniqueConstraint"

        # Check that one of them contains athlete_id and metric_date
        found_constraint = False
        for uc in unique_constraints:
            if "athlete_id" in uc.columns and "metric_date" in uc.columns:
                found_constraint = True
                break

        assert found_constraint, "Expected unique constraint on (athlete_id, metric_date)"

    @pytest.mark.asyncio
    async def test_wellness_model_has_cascade_delete(self):
        """Test that AthleteWellness has cascade delete on athlete_id foreign key."""
        athlete_id_column = AthleteWellness.__table__.columns["athlete_id"]

        # Check that the foreign key exists and has cascade delete
        fk = athlete_id_column.foreign_keys
        assert len(fk) > 0, "Expected foreign key on athlete_id"

        fk_constraint = list(fk)[0]
        assert fk_constraint.ondelete is not None, "Expected ondelete on athlete_id foreign key"