"""create_base_tables

Revision ID: 62e4a6cfd7b2
Revises: f5445c94c158
Create Date: 2026-04-18 04:05:07.004844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e4a6cfd7b2'
down_revision: Union[str, None] = 'f5445c94c158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
