"""create_tables_from_models

Revision ID: 96d888aad9dd
Revises: 62e4a6cfd7b2
Create Date: 2026-04-18 04:09:14.795200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96d888aad9dd'
down_revision: Union[str, None] = '62e4a6cfd7b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
