"""add_athlete_physiology_table

Revision ID: e2b4c9f923f8
Revises: 34434d79ba41
Create Date: 2026-05-06 15:37:59.855589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2b4c9f923f8'
down_revision: Union[str, None] = '34434d79ba41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_athlete_id_started_at'), table_name='activities')
    op.drop_index(op.f('athlete_wellness_metric_date_idx'), table_name='athlete_wellness')
    op.create_unique_constraint('uq_athlete_wellness_date', 'athlete_wellness', ['athlete_id', 'metric_date'])
    op.create_table('athlete_physiology',
    sa.Column('id', sa.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('athlete_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('ftp', sa.Integer(), nullable=True),
    sa.Column('lt1', sa.Integer(), nullable=True),
    sa.Column('lt2', sa.Integer(), nullable=True),
    sa.Column('vo2_max', sa.Float(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'GARMIN', 'WHOOP', 'OURA', 'POLAR', name='wellnesssource', length=20), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_athlete_physiology_athlete_id', 'athlete_physiology', ['athlete_id'], unique=False)
    op.create_index('ix_athlete_physiology_effective_from_to', 'athlete_physiology', ['athlete_id', 'effective_from', 'effective_to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_athlete_wellness_date', 'athlete_wellness', type_='unique')
    op.create_index(op.f('athlete_wellness_metric_date_idx'), 'athlete_wellness', [sa.literal_column('metric_date DESC')], unique=False)
    op.create_index(op.f('ix_activities_athlete_id_started_at'), 'activities', ['athlete_id', 'started_at'], unique=False)
    # ### end Alembic commands ###
